### ISSUE TITLE
Not recognized column type

### ISSUE THREAD

**Issue by jawira** [edyan/neuralyzer#23]
Hello, I tried to generate a config file with `config:generate` but I got this error:

> In AbstractPlatform.php line 454:
>                                                                                                            
>  Unknown database type _int4 requested, Doctrine\DBAL\Platforms\PostgreSQL100Platform may not support it.  

As you can see, `_int4` is not recognized as a valid column type. In _Symfony_ you can fix this configuring  `mapping_types`.

```yaml
# config/packages/doctrine.yaml
doctrine:
    dbal:
        mapping_types:
            _int4: string
```

Does _neuralizer_ have something like this? Thank you.
